- name: Install Dependences Kubernetes
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - awscli
    - kubectl
    - kops
    - php
    - nginx
    - database
    - k8s
    
 
#- name: Install MySQL
#  hosts: db
#  remote_user: ubuntu
#  become: yes
#  become_method: sudo
#  roles:
#    - mysql

