- name: install k8s
  command: kops create cluster --zones={{ available_zone }} --node-count={{ node_count }} --master-count={{ master_count }} --node-size={{ node_size }} --master-size={{ master_size }} --name={{ cluster_name }} --state={{ state_store }} --ssh-public-key=~/.ssh/id_rsa.pub 

- name: update cluster
  command: kops update cluster --name {{ cluster_name }} --state {{ state_store }} --yes
