- name: Install Python simplejson
  apt:
    pkg: python-simplejson
    state: present
    update_cache: true


- name: copy dump SQL file to tmp
  template:
    src: dump.sql
    dest: /var/tmp/


- name: Run SQL commands to create database {{ pesbuk_db_name }}
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: present




- name: Deploy Database Dump SQL to remote server
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: import
